sonarqube-check:
  tags:
    - sonar-scanner-windows
  stage: sonarqube
  variables:
    SONAR_SOURCEENCODING: "UTF-8" 
    SONAR_PROJECTNAME: "masa.officialwebsite"
    SONAR_PROJECTKEY: "cicd_masa.officialwebsite_AYIkcRVbMgcW0bQ3LsBP"
    SONAR_PROJECTVERSION: "1.0"
    SONAR_SOURCES: ". "
  script:
    - echo $SONAR_HOST_URL
    - ls
    - pwd 
    - sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.sourceEncoding=$SONAR_SOURCEENCODING -D sonar.projectName$SONAR_PROJECTNAME  -D sonar.projectVersion=$SONAR_PROJECTVERSION -D sonar.sources=.  -D sonar.login=$SONAR_LOGIN    -D sonar.projectKey=$SONAR_PROJECTKEY
  allow_failure: true
  only:
    - *