# include:
#   - project: 'louzhijian/devops'
#     ref: master
#     file: 'devops/sonar-scanner.yml'

stages:
#   - sonarqube
  - docker-dev
  - deploy-dev
  - deploy-test
  - docker-prd
  - deploy-prd

variables:
  DOCKER_Offical_WebSite_PATH: src/MASA.OfficialWebsite.Server/Dockerfile
  NEW_IMAGE_Offical_WebSite_Dev: $CI_ALI_REGISTRY_DOMAIN/masa/masa-official-website:dev-$CI_PIPELINE_ID
  # NEW_IMAGE_Offical_WebSite: $CI_ALI_REGISTRY_DOMAIN/masa/masa-official-website:$CI_COMMIT_TAG
  NEW_IMAGE_Offical_WebSite: $CI_ALI_REGISTRY_DOMAIN/masa/masa-official-website:$CI_PIPELINE_ID


docker-build-dev:
  stage: docker-dev
  tags:
    - linux-shell
  before_script:
    - docker login --username=$CI_ALI_REGISTRY_USER --password=$CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN
  only:
    - main  
  script:
    - docker build -f $DOCKER_Offical_WebSite_PATH -t $NEW_IMAGE_Offical_WebSite_Dev .
    - docker push $NEW_IMAGE_Offical_WebSite_Dev 
  after_script:
    - docker rmi $NEW_IMAGE_Offical_WebSite_Dev   


deploy-dev:
  stage: deploy-dev
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER --password-stdin $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - main  
  script:
    - echo $KUBE_CONFIG_DEV_YDY  | base64 -d > ./config
    - kubectl --kubeconfig ./config set image deployment/masa-official-website masa-official-website=$NEW_IMAGE_Offical_WebSite_Dev -n masastack-dev
  retry: 2

docker-build-prd:
  stage: docker-prd
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - main  
  script:
    - docker build -f $DOCKER_Offical_WebSite_PATH -t $NEW_IMAGE_Offical_WebSite .
    - docker push $NEW_IMAGE_Offical_WebSite
  after_script:
    - docker rmi $NEW_IMAGE_Offical_WebSite
  


deploy-prd:
  stage: deploy-prd
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - main
  script:
    - echo $KUBE_CONFIG_BLAZOR_PRD | base64 -d > ./config
    - kubectl --kubeconfig ./config set image deployment/masa-official-website masa-official-website=$NEW_IMAGE_Offical_WebSite -n masa-official-website
  retry: 2
  when: manual
